### ISSUE TITLE
dataset folder does not exist

### ISSUE THREAD

**Issue by Mahmoud-Magdy-deeplearning** [gsasikiran/Comparative-Evaluation-of-Pretrained-Transfer-Learning-Models-on-ASAG#1]
I can not find the dataset folder neither dataset files so I could not run the project.

**Comment by gsasikiran** [comment]
You can download the dataset [here](https://web.eecs.umich.edu/~mihalcea/downloads.html) under Automatic Short Answer Grading, as I have already mentioned in the ReadMe.

**Comment by Mahmoud-Magdy-deeplearning** [comment]
I followed the steps but I want to know how can I get this folder "**dataset**" which contains mohler_dataset_edited.csv & answers_with_similarity_score.csv because I can not find these files

**Comment by gsasikiran** [comment]
Updated dataset
