### ISSUE TITLE
Facing an issue while importing 'bert_embedding'

### ISSUE THREAD

**Issue by KishanReddy9** [gsasikiran/Comparative-Evaluation-of-Pretrained-Transfer-Learning-Models-on-ASAG#3]

**Comment by gsasikiran** [comment]
Can you provide the error you are facing?

**Comment by KishanReddy9** [comment]
When I try to install it in Pycharm , the error description is as follows:

Collecting bert-embedding
  Using cached bert_embedding-1.0.1-py3-none-any.whl (13 kB)
Collecting mxnet==1.4.0
  Using cached mxnet-1.4.0-py2.py3-none-win_amd64.whl (21.9 MB)
Collecting numpy==1.14.6
  Using cached numpy-1.14.6.zip (4.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting gluonnlp==0.6.0
  Using cached gluonnlp-0.6.0-py3-none-any.whl
Requirement already satisfied: typing==3.6.6 in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages (from bert-embedding) (3.6.6)
Collecting graphviz<0.9.0,>=0.8.1
  Using cached graphviz-0.8.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: requests<2.19.0,>=2.18.4 in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages (from mxnet==1.4.0->bert-embedding) (2.18.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.4.0->bert-embedding) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.4.0->bert-embedding) (2020.12.5)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.4.0->bert-embedding) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.4.0->bert-embedding) (3.0.4)
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py): started
  Building wheel for numpy (setup.py): finished with status 'error'
  Running setup.py clean for numpy
Failed to build numpy
Installing collected packages: numpy, graphviz, mxnet, gluonnlp, bert-embedding
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
  Running setup.py install for numpy: started
  Running setup.py install for numpy: finished with status 'error'
  Rolling back uninstall of numpy
  Moving to c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages\numpy-1.18.5.dist-info\
   from C:\Users\Admin\PycharmProjects\pythonProject\venv\Lib\site-packages\~umpy-1.18.5.dist-info
  Moving to c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages\numpy\
   from C:\Users\Admin\PycharmProjects\pythonProject\venv\Lib\site-packages\~umpy
  Moving to c:\users\admin\pycharmprojects\pythonproject\venv\scripts\f2py.exe
   from C:\Users\Admin\AppData\Local\Temp\pip-uninstall-vm01o5f4\f2py.exe

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [240 lines of output]
  Running from numpy source directory.
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\misc_util.py:464: SyntaxWarning: "is" with a literal. Did you mean "=="?
    return is_string(s) and ('*' in s or '?' is s)
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  blis_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blis not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  openblas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    self.calc_info()
  blas_src_info:
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE
  
  'svnversion' is not recognized as an internal or external command,
  operable program or batch file.
  'svnversion' is not recognized as an internal or external command,
  operable program or batch file.
  non-existing path in 'numpy\\distutils': 'site.cfg'
  F2PY Version 2
  lapack_opt_info:
  lapack_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  openblas_lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  openblas_clapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas,lapack not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build\src.win-amd64-3.8
  creating build\src.win-amd64-3.8\numpy
  creating build\src.win-amd64-3.8\numpy\distutils
  building library "npymath" sources
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
  error: subprocess-exited-with-error
  
  python setup.py clean did not run successfully.
  exit code: 1
  
  [10 lines of output]
  Running from numpy source directory.
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for numpy
  error: subprocess-exited-with-error
  
  Running setup.py install for numpy did not run successfully.
  exit code: 1
  
  [245 lines of output]
  Running from numpy source directory.
  
  Note: if you need reliable uninstall behavior, then install
  with pip instead of using `setup.py install`:
  
    - `pip install .`       (from a git repo or downloaded source
                             release)
    - `pip install numpy`   (last NumPy release on PyPi)
  
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\misc_util.py:464: SyntaxWarning: "is" with a literal. Did you mean "=="?
    return is_string(s) and ('*' in s or '?' is s)
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  blis_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blis not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  openblas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  blas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries blas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    self.calc_info()
  blas_src_info:
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE
  
  'svnversion' is not recognized as an internal or external command,
  operable program or batch file.
  'svnversion' is not recognized as an internal or external command,
  operable program or batch file.
  non-existing path in 'numpy\\distutils': 'site.cfg'
  F2PY Version 2
  lapack_opt_info:
  lapack_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  openblas_lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  openblas_clapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas,lapack not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE
  
  atlas_3_10_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE
  
  atlas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE
  
  atlas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\Users\Admin\PycharmProjects\pythonProject\venv\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE
  
  lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack not found in ['C:\\Users\\Admin\\PycharmProjects\\pythonProject\\venv\\lib', 'C:\\']
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Temp\pip-install-jc289p_r\numpy_539db4e8e95247c99c3ff0360ea74e53\numpy\distutils\system_info.py:624: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE
  
  C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running install
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  building library "npymath" sources
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\admin\pycharmprojects\pythonproject\venv\lib\site-packages
error: legacy-install-failure

Encountered error while trying to install package.

numpy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by KishanReddy9** [comment]
Downgraded the python version from 3.8.x to 3.7.x and able to import now
